name: Run E2E tests

on:
  push:
    branches: [temp]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run db and web containers
        run: |
          cd e2e
          docker-compose up -d
      - name: Wait for Openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:9000/openmrs/login.htm)" != "200" ]]; do sleep 10; done
      - name: Run dev server
        run: yarn start --backend "http://localhost:9000" &
      - name: Checkout test-3refapp repo
        uses: actions/checkout@v3
        with:
          repository: jayasanka-sack/openmrs-test-3refapp
          path: tests
      - name: Installing dependencies
        run: npm install
        working-directory: tests/packages/cypress
      - name: Run tests
        run: CYPRESS_BASE_URL=http://localhost:8080/openmrs/spa cypress open --env API_BASE_URL=http://localhost:8080/openmrs/ws/rest/v1
        working-directory: tests/packages/cypress
      - name: Upload screen recordings of failed tests
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Screen recordings of failed tests
          path: |
            tests/packages/packages/cypress/cypress/videos
            tests/packages/packages/cypress/cypress/screenshots
